# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CSGO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CSGO

  pod 'Alamofire'
  pod 'SGImageCache'

  target 'CSGOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSGOUITests' do
    # Pods for testing
  end

end
